services:
    rabbitmq:
       image: rabbitmq:3-management-alpine
       #container_name: rabbitmq_management
       ports:
        - 25672:25672 # (erlang) communication between the nodes and CLI tool
        - 15672:15672 # communication with the web management API
        - 5672:5672
       environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=pwd
       restart: always
